### ISSUE TITLE
游客的打扰

### ISSUE THREAD

**Issue by LXHoooo** [Jianx-Gao/sdu_homework#1]
大佬您好：
    我想请问一下您做这个项目的第一手知识是怎么来的呢？是通过看论文还是基于开源项目呢？我一直比较困惑怎么自己去获取第一手学习知识，很多时候都是通过他人的一些视频博客啥的，不知道大佬能否解答一下，不胜感激

**Comment by JianxGao** [comment]
我也是新手。我觉得论文和开源项目都要看看，以论文为主吧。

**Comment by LXHoooo** [comment]
> 我也是新手。我觉得论文和开源项目都要看看，以论文为主吧。
好的，谢谢。
那能否耽误您点时间？能不能具体展开下这个您做这个树莓派的心音诊断的时候怎么解决里面的技术问题的呢？
