### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by zj2050** [Jianx-Gao/sdu_homework#2]
1、test.py

**Comment by JianxGao** [comment]
I haven't reviewed the code for about 3 years. I forget most of the details of this work. Also, this repo only uses for recording my undergraduate life and homework.

**Comment by JianxGao** [comment]
close

**Comment by zj2050** [comment]
那能方便告知，你切割之后的 2.5s文件都单独保存为另外一个 正常（或者异常）的信号文件，作为下一步训练文件吗？
